version: '3.5'

services:
  marketplace-server:
    build: ./provisioning/marketplace_server/development
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - ./:/application:cached

  queue-server:
    build: ./provisioning/marketplace_server/development
    command: php artisan queue:work
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=marketplace
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx:1.15
    ports:
      - '8000:8000'
    volumes:
      - ./provisioning/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - marketplace-server

  node-server:
    image: node:10.9
    ports:
      - '8888:8888'
    working_dir: /application
    volumes:
      - .:/application:cached
    depends_on:
      - marketplace-server

  redis:
    image: redis:4.0
    ports:
      - '6379:6379'
